[tool.poetry]
name = "beginner"
version = "0.1.0"
description = ""
authors = ["engineer <tashirka1@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.10,<3.11"
tensorflow = "^2.11.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
